# Generated by Django 4.2.3 on 2023-08-01 01:33

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_agrege_usuario_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='apellido',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('cantidad', models.SmallIntegerField(default=1, verbose_name='Cantidad o Stock')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, unique=True, verbose_name='producto')),
                ('disponible', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriamodel')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
