# Generated by Django 4.2.3 on 2023-08-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_creacion_tablas_productos_y_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='tipoUsuario',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CLIENTE', 'CLIENTE')], default='ADMIN', max_length=100),
        ),
    ]
