# Generated by Django 4.2.3 on 2023-08-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_agrege_columna_tabla_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='disponible',
        ),
    ]
